service: calendar-formatter
app: calendar-formatter

custom:
  token: ${file(./secrets/secrets.json):token}
  bucket: ${file(./secrets/secrets.json):bucket}
  chatId: ${file(./secrets/secrets.json):chatId}

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
      Resource: "*"

package:
  exclude:
    - ./**
  include:
    - handler.js
    - src/**
    - node_modules/**
    - semesters.json

functions:
  api:
    handler: handler.formatter
    events:
      - schedule: cron(0 */6 * * ? *)
    environment:
      BUCKET: ${self:custom.bucket}
      BOT_TOKEN: ${self:custom.token}
      CHAT_ID: ${self:custom.chatId}
  bot:
    handler: handler.bot
    events:
      - http:
          path: bot
          method: ANY
          cors: true
    environment:
      BOT_TOKEN: ${self:custom.token}
