service: calendar-formatter
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  timeout: 20
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:*
            - lambda:InvokeFunction
          Resource: "*"
  environment:
    REGION: ${opt:region, self:provider.region}
    BUCKET: ${self:custom.bucket}
    BOT_TOKEN: ${file(./secrets/secrets.json):token}
    CHAT_ID: ${file(./secrets/secrets.json):chatId}
    CENTURIA: ${file(./secrets/secrets.json):centuria}

custom:
  bucket: ${file(./secrets/secrets.json):bucket}
  s3:
    port: 8000
    directory: /tmp
  webpack:
    webpackConfig: "./webpack.config.js"
    includeModules: true
    packager: "yarn"

plugins:
  - serverless-s3-local
  - serverless-offline
  - serverless-webpack

functions:
  timetableApi:
    handler: src/handler.timetableFormatter
    events:
      - schedule: cron(0 0 * * ? *)
  mensaApi:
    handler: src/handler.mensaFormatter
    events:
      - schedule: cron(0 0 * * ? *)
  bot:
    handler: src/handler.bot
    events:
      - http:
          path: bot
          method: ANY
          cors: true

resources:
  Resources:
    S3CalendarBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
        WebsiteConfiguration:
          IndexDocument: index.html
