name: Deploy master

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install
        run: npm ci
        env:
          CI: true

      - name: Run tests
        run: npm test

      - name: Run app stetup
        run: npm run setup
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Serverless create domain
        uses: serverless/github-action@master
        with:
          args: create_domain
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
