name: Deploy master

on:
  release:
    types:
      - published

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Decrypt secrets
        run: ./.github/scripts/decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.ENC_PASSPHRASE }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install and test
        run: |
          npm ci
          npm test
        env:
          CI: true
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
