name: Test PR

on: pull_request

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install
        run: yarn
        env:
          CI: true

      - name: Run tests
        run: yarn test
