name: Test PR

on: pull_request

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install
        run: yarn
        env:
          CI: true

      - name: Run app setup
        run: yarn setup --passphrase ${{ secrets.PASSPHRASE }}
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DOMAIN: ${{ secrets.DOMAIN }}
        
      - name: Run tests
        run: yarn test
